---
title: "Clinical Sample Metadata"
author: "Sara Gosline"
date: "2025-09-16"
output: html_document
---

Here we'll create some small summary statistics of the new clinical samples.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(synapser)
library(readxl)
library(ggplot2)
library(dplyr)

```

## Grab and parse metadata
Metadata is currently on synapse in an excel file under syn68733653. 


```{r cars}
synLogin()

mfile <- readxl::read_xlsx(synapser::synGet('syn69058992')$path)

#cohort <- list(Relapse='darkblue',Refractory='darkgreen',`Response - no relapse`='goldenrod')
vstats <- list(Alive='orange3',Dead='plum4',LTFU='darkgrey')
```

```{r plots}
mfile |>
  mutate(`Days of remission`=as.numeric(`duration of remission post hma-ven (days)`))|>
  subset(`sub-cohort PNNL`%in%c('Relapse','Refractory','Response - no relapse'))|>
ggplot(aes(x=`sub-cohort PNNL`,
                  y=`Days of remission`,
                  fill=vitalStatus))+
  scale_fill_manual(values=vstats)+
          geom_boxplot()+
   theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggsave('clinMetaSumm.png')

mfile |>
  mutate(`Days of remission`=as.numeric(`duration of remission post hma-ven (days)`))|>
  subset(`sub-cohort PNNL`%in%c('Relapse','Refractory','Response - no relapse'))|>
  ggplot(aes(x=`sub-cohort PNNL`,
                  y=`Days of remission`,
           size=`overallSurvival(days)`,
                  col=vitalStatus))+
          geom_jitter()+
  scale_color_manual(values=vstats)+
   theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave('clinMetaSummSurv.png')

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
