

```{r}
library(dplyr)
library(MSnSet.utils)
library(msigdbr)

source("helper_scripts.R")
source("synapseUtil.R")
source("plotting enrichment.R")

syn<-synapseLogin()
## Load corrected exp25 dataset
# m_corrected <- readRDS("msnset_4patients_corrected.RDS")
m_corrected <- readRDS(syn$get("syn64605135")$path)

```


## Comparing diffexp in 4patients to diffexp in exp 18


```{r}

treatment_contrasts <- c("D-UT", "G-UT", "V-UT", "GV-UT", "GD-UT", "DV-UT", "GVD-UT")
treats=list(`D-UT`='Decitabine',`G-UT`='Gilteritinib', 
            `V-UT`='Venetoclax', `GV-UT`='Gilteritinib+Venetoclax', 
            `GD-UT`='Gilteritnib+Decitabine', 
            `DV-UT`='Decitabine+Venetoclax', 
            `GVD-UT`='Gilteritinib+Decitabine+Venetoclax')
# pat_diffexp <- diffexp_helper(m_corrected, "Treatment", treatment_contrasts)
# write.table(pat_diffexp, "patient_lines_diffexp.txt", sep = "\t", quote = F, row.names = F)
# pat_diffexp <- read.table("patient_lines_diffexp.txt", sep = "\t", header = T)
pat_diffexp <- read.table(syn$get("syn64605136")$path, sep = "\t", header = T)|>
  mutate(Treatment=sapply(contrast,function(x) treats[[x]]))

## For counts
table(pat_diffexp %>% filter(adj.P.Val < 0.05) %>% pull(contrast),
      pat_diffexp %>% filter(adj.P.Val < 0.05) %>% pull(logFC) > 0)

# exp18_diffexp <- read.table("exp18_diffexp_global.txt", sep = "\t", header = T)
exp18_diffexp <- read.table(syn$get("syn51514584")$path, sep = "\t", header = T)
# cohort_diffexp <- read.table("210cohort_ven_resistant_sensitive_diffexp.txt", sep = "\t", header = T)
cohort_diffexp <- read.table(syn$get("syn64605133")$path, sep = "\t", header = T)
```




## Diffexp counts in 4patients



```{r}
treatment_contrasts <- c("D-UT", "G-UT", "V-UT", "GV-UT", "GD-UT", "DV-UT", "GVD-UT")
## Diffexp count barplot here!!
table(pat_diffexp$Treatment, pat_diffexp$adj.P.Val < 0.05)

diffexp_counts <- pat_diffexp %>%
   filter(!is.na(adj.P.Val),
          adj.P.Val < 0.05) %>%
   mutate(positive = logFC > 0) %>%
   group_by(Treatment, positive) %>% summarize(total = n()) %>% as.data.frame()
rownames(diffexp_counts) <- paste(diffexp_counts$Treatment, diffexp_counts$positive)

padding_df <- data.frame(Treatment = rep(unlist(treats), 2), positive = c(rep(TRUE, length(treats)),
                                                                              rep(FALSE, length(treats))),
                         total = rep(0, 2*length(treats)))
rownames(padding_df) <- paste(padding_df$Treatment, padding_df$positive)

diffexp_counts <- rbind(diffexp_counts, padding_df[setdiff(rownames(padding_df), rownames(diffexp_counts)), ]) 
diffexp_counts <- diffexp_counts %>%
   mutate(group = case_when(positive ~ "Over",
                            TRUE ~ "Under"),
          group = paste(Treatment, group))

ggplot(diffexp_counts %>% filter(positive), aes(x = Treatment, y = total)) + geom_bar(stat = 'identity', width = 0.8, color = "grey", fill = "firebrick2") +
   theme(axis.text.x = element_text(size = 13, angle = 45, hjust = 1),
         axis.text.y = element_text(size = 10)) + ggtitle("Number of significant overexpressed features")

ggplot(diffexp_counts %>% filter(!positive), aes(x = Treatment, y = total)) + geom_bar(stat = 'identity', width = 0.8, color = "grey", fill = "steelblue3") +
   theme(axis.text.x = element_text(size = 13, angle = 45, hjust = 1),
         axis.text.y = element_text(size = 10)) + ggtitle("Number of significant underexpressed features")

```





## Extracting Venetoclax signature from ex vivo and applying to 210 cohort


```{r}
# pat_diffexp <- read.table("patient_lines_diffexp.txt", sep = "\t", header = T)
pat_diffexp <- read.table(syn$get("syn64605136")$path, sep = "\t", header = T)
# cohort_diffexp <- read.table("210cohort_ven_resistant_sensitive_diffexp.txt", sep = "\t", header = T)
cohort_diffexp <- read.table(syn$get("syn64605133")$path, sep = "\t", header = T)


complete_V_UT_features <- complete.cases(exprs(m_corected[, m_corected$Treatment %in% c("UT", "V")]))
complete_V_UT_features <- featureNames(m_corected)[complete_V_UT_features]
resistant_markers <- pat_diffexp %>% filter(contrast == "V-UT", 
                                            feature %in% cohort_diffexp$feature) %>% 
   arrange(t_test_pval) %>%
   filter(logFC > 0) %>% slice(1:10) %>% pull(feature)

sensitive_markers <- pat_diffexp %>% filter(contrast == "V-UT", 
                                            feature %in% cohort_diffexp$feature) %>% 
   arrange(t_test_pval) %>%
   filter(logFC < 0) %>% slice(1:10) %>% pull(feature)

# m_210 <- readRDS("210_cohort_global.RDS")
m_210 <- readRDS(syn$get("syn64605141")$path)
drug_data <- read.csv(syn$get("syn51674470")$path) %>% filter(inhibitor == "Venetoclax")
# drug_data <- read.csv("210_cohort_drug_auc_syn51674470.csv") %>% filter(inhibitor == "Venetoclax")
unique(drug_data$sample_id) %>% length()
nrow(drug_data)

sensitive_signal <- apply(exprs(m_210)[sensitive_markers, ], 2, mean)
resistant_signal <- apply(exprs(m_210)[resistant_markers, ], 2, mean)
signal <- resistant_signal - sensitive_signal

pData(m_210)[names(signal), "model_signal"] <- signal
pData(m_210)[drug_data$sample_id, "Venetoclax_auc"] <- drug_data$auc
cor(m_210$Venetoclax_auc, m_210$model_signal, "complete.obs")
cor(m_210$Venetoclax_auc, m_210$model_signal, "complete.obs", method = "spearman")
plot(m_210$Venetoclax_auc, m_210$model_signal)

pData(m_210)$group <- "NA"
pData(m_210)[pData(m_210) %>% filter(Venetoclax_auc < 111) %>% pull(Barcode.ID), "group"] <- "Sensitive"
pData(m_210)[pData(m_210) %>% filter(Venetoclax_auc >= 111,
                                     Venetoclax_auc < 200) %>% pull(Barcode.ID), "group"] <- "Middle"
pData(m_210)[pData(m_210) %>% filter(Venetoclax_auc >= 200) %>% pull(Barcode.ID), "group"] <- "Resistant"

plot_df <- data.frame(sample = m_210$Barcode.ID, model = m_210$model_signal, 
                      Ven_AUC = m_210$Venetoclax_auc, VEN_group = m_210$group, FLT3 = m_210$FLT3.ITD) %>% filter(VEN_group != "NA") %>%
   mutate(VEN_group = factor(VEN_group, levels = c("Sensitive", "Middle", "Resistant")),
          VEN_group2 = case_when(VEN_group == "Resistant" ~ "Resistant",
                                 TRUE ~ "Sensitive + Middle"),
          VEN_group2 = factor(VEN_group2, levels = c("Sensitive + Middle", "Resistant")))

ggplot(plot_df, aes(x = VEN_group, y = model)) + geom_boxplot() + ylab("4 patients V-UT signature")
ggplot(plot_df, aes(x = VEN_group, y = model, fill = FLT3)) + geom_boxplot() + ylab("4 patients V-UT signature")
ggplot(plot_df, aes(x = VEN_group, y = model)) + geom_violin()

ggplot(plot_df, aes(x = VEN_group2, y = model)) + geom_boxplot() + ylab("4 patients V-UT signature")
ggplot(plot_df, aes(x = VEN_group2, y = model)) + geom_violin()

t.test(model ~ VEN_group, data = plot_df %>% filter(VEN_group %in% c("Resistant", "Middle")), 
       alternative = "two.sided", var.equal = TRUE)[[3]]
t.test(model ~ VEN_group, data = plot_df %>% filter(VEN_group %in% c("Resistant", "Sensitive")), 
       alternative = "two.sided", var.equal = TRUE)[[3]]
t.test(model ~ VEN_group, data = plot_df %>% filter(VEN_group %in% c("Middle", "Sensitive")), 
       alternative = "two.sided", var.equal = TRUE)[[3]]


t.test(model ~ VEN_group2, data = plot_df %>% filter(VEN_group2 %in% c("Resistant", "Sensitive + Middle")), 
       alternative = "two.sided", var.equal = TRUE)[[3]]

plot_df_combine <- plot_df
plot_df_combine$model_ven <- plot_df$model
rownames(plot_df_combine) <- plot_df_combine$sample

```



## GSEA enrichment



```{r}
t2g_hallmark <- msigdbr(species = "Homo sapiens", category = "H") %>%
  dplyr::select(gs_name, gene_symbol)

t2g_gobp <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "BP") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_gocc <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "CC") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_gomf <- msigdbr(species = "Homo sapiens", category = "C5", subcategory = "MF") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_wikipath <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "WIKIPATHWAYS") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))

t2g_reactome <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "REACTOME") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))


t2g_kegg <- msigdbr(species = "Homo sapiens", category = "C2", subcategory = "KEGG") %>% 
  dplyr::select(gs_name, gene_symbol) %>%
  mutate(gs_name = gsub("_", " ", gs_name))


all_t2gs <- list(t2g_gobp, t2g_gocc, t2g_gomf, t2g_hallmark, t2g_kegg, t2g_reactome)
names(all_t2gs) <- c("GOBP", "GOCC", "GOMF", "Hallmark", "KEGG", "Reactome")

```


```{r}
## Getting the GSEA results

# for (t2g_name in names(all_t2gs)){
#   GSEA_helper(m_corrected, treatment_contrasts, t2g = all_t2gs[[t2g_name]],
#               t2g_name = paste0("ptrc_4patient_lines_", t2g_name), "Treatment")
# }


# GSEA_global <- rbind(read.table("GSEA tables/GSEA_ptrc_4patient_lines_GOBP_combined.txt", sep = "\t") %>% 
#                        mutate(DB = "GOBP"),
#                      read.table("GSEA tables/GSEA_ptrc_4patient_lines_GOCC_combined.txt", sep = "\t") %>% 
#                        mutate(DB = "GOCC"),
#                      read.table("GSEA tables/GSEA_ptrc_4patient_lines_GOMF_combined.txt", sep = "\t") %>% 
#                        mutate(DB = "GOMF"),
#                      read.table("GSEA tables/GSEA_ptrc_4patient_lines_Hallmark_combined.txt", sep = "\t") %>% 
#                        mutate(DB = "Hallmark"),
#                      read.table("GSEA tables/GSEA_ptrc_4patient_lines_KEGG_combined.txt", sep = "\t") %>% 
#                        mutate(DB = "KEGG"),
#                      read.table("GSEA tables/GSEA_ptrc_4patient_lines_Reactome_combined.txt", sep = "\t") %>% 
#                        mutate(DB = "Reactome"))
# write.table(GSEA_global, "GSEA tables/patient_lines_GSEA.txt", sep = "\t", quote = F, row.names = F)

# GSEA_global <- read.table("GSEA tables/patient_lines_GSEA.txt", sep = "\t", header = T)
GSEA_global <- read.table(syn$get("syn64605143")$path, sep = "\t", header = T)
# GSEA_210_ven <- read.table("GSEA tables/GSEA_ven_resistant_vs_sensitive_210cohort.txt", sep = "\t", header = T)
GSEA_210_ven <- read.table(syn$get("syn64605142")$path, sep = "\t", header = T)

```




Plotting the GSEA results



```{r}
enrichment_df <- GSEA_global %>%
   filter(contrast == "V-UT",
          DB == "Hallmark") %>% 
   mutate(pathway = sub("HALLMARK_", "", Description),
          pathway = gsub("_", " ", pathway),
          enrichment = NES,
          adj_p_val = p.adjust) %>%
   arrange(adj_p_val)
plot_enrichment_result(enrichment_df, "Venetoclax - Untreated", enrichment_title = "Hallmark GSEA Venetoclax - Untreated")

enrichment_df <- GSEA_210_ven %>%
   filter(contrast == "Resistant-Sensitive",
          DB == "Hallmark") %>% 
   mutate(pathway = sub("HALLMARK_", "", Description),
          pathway = gsub("_", " ", pathway),
          enrichment = NES,
          adj_p_val = p.adjust) %>%
   arrange(adj_p_val)
plot_enrichment_result(enrichment_df, "Resistant - Sensitive", 
                       enrichment_title = "Hallmark GSEA Resistant - Sensitive (210 cohort)")



enrichment_df <- GSEA_global %>%
   filter(contrast == "V-UT",
          DB == "Reactome") %>% 
   mutate(pathway = sub("REACTOME ", "", Description),
          pathway = gsub("_", " ", pathway),
          enrichment = NES,
          adj_p_val = p.adjust) %>%
   arrange(adj_p_val)
plot_enrichment_result(enrichment_df, "Venetoclax - Untreated", enrichment_title = "Reactome GSEA Venetoclax - Untreated")

enrichment_df <- GSEA_210_ven %>%
   filter(contrast == "Resistant-Sensitive",
          DB == "Reactome") %>% 
   mutate(pathway = sub("REACTOME ", "", Description),
          pathway = gsub("_", " ", pathway),
          enrichment = NES,
          adj_p_val = p.adjust) %>%
   arrange(adj_p_val)
plot_enrichment_result(enrichment_df, "Resistant - Sensitive", 
                       enrichment_title = "Reactome GSEA Resistant - Sensitive (210 cohort)")


```


### Over representation of differential expression


```{r}

## Using ex vivo

diffexp_ora <- pat_diffexp %>% mutate(adj_pval = adj.P.Val) %>%
   select(feature, logFC, adj_pval, contrast)

ora_results_global <- rbind(ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_gobp) %>% 
                        mutate(DB = "GOBP"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_gocc) %>% 
                        mutate(DB = "GOCC"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_gomf) %>% 
                        mutate(DB = "GOMF"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_hallmark) %>% 
                        mutate(DB = "Hallmark"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_kegg) %>% 
                        mutate(DB = "KEGG"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_reactome) %>% 
                        mutate(DB = "Reactome"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_wikipath) %>% 
                        mutate(DB = "Wikipath"))


## Using 210 cohort
diffexp_ora <- cohort_diffexp %>% mutate(adj_pval = adj.P.Val) %>%
   select(feature, logFC, adj_pval, contrast)

ora_cohort_venetoclax <- rbind(ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_gobp) %>% 
                        mutate(DB = "GOBP"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_gocc) %>% 
                        mutate(DB = "GOCC"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_gomf) %>% 
                        mutate(DB = "GOMF"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_hallmark) %>% 
                        mutate(DB = "Hallmark"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_kegg) %>% 
                        mutate(DB = "KEGG"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_reactome) %>% 
                        mutate(DB = "Reactome"),
                     ORA_helper(diffexp_ora, diffexp_ora$feature, t2g_wikipath) %>% 
                        mutate(DB = "Wikipath"))

```



```{r}
#######################################


## V-UT compared to Ven Resistant vs Sensitive in 210 cohort.
ven_res_vs_sen_pathway <- ora_cohort_venetoclax %>% filter(contrast == "Resistant-Sensitive", p.adjust < 0.05) 
View(ora_results_global %>% filter(ID %in% ven_res_vs_sen_pathway$ID, contrast == "V-UT"))

V_UT_pathways <- ora_results_global %>% filter(contrast == "V-UT", p.adjust < 0.05) 
View(ora_cohort_venetoclax %>% filter(ID %in% V_UT_pathways$ID, contrast == "Resistant-Sensitive"))

```





